apiVersion: v1
kind: ConfigMap
metadata:
  name: chainward-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chainward.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  PORT: "{{ .Values.api.port }}"
  REDIS_URL: "redis://redis:6379"
  CORS_ORIGINS: "http://{{ .Values.domain }}{{ if .Values.publicDomain }},https://{{ .Values.publicDomain }}{{ end }}"
  API_INTERNAL_URL: "http://api:{{ .Values.api.port }}"
